import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
// import './../globals.css';
import SearchHeader from '@/components/SearchHeader';
import { PropsWithChildren } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Search ',
  description: 'Generated by Sepide Kia',
  icons: { icon: '/favicon.svg' },
};

export default function SearchLayout({ children }: PropsWithChildren) {
  return (
    <div className={inter.className}>
      <SearchHeader />
      {children}
    </div>
  );
}
